# Generated by Django 6.0.7 on 2026-07-14 14:20

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='company_address',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='user',
            name='company_logo',
            field=models.ImageField(blank=True, null=True, upload_to='company_logos/'),
        ),
        migrations.AddField(
            model_name='user',
            name='default_currency',
            field=models.CharField(choices=[('USD', 'USD — US Dollar'), ('EUR', 'EUR — Euro'), ('GBP', 'GBP — British Pound'), ('CAD', 'CAD — Canadian Dollar'), ('AUD', 'AUD — Australian Dollar'), ('PKR', 'PKR — Pakistani Rupee'), ('INR', 'INR — Indian Rupee'), ('AED', 'AED — UAE Dirham')], default='USD', max_length=3),
        ),
        migrations.AddField(
            model_name='user',
            name='default_tax_rate',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=5),
        ),
    ]
