# Generated by Django 6.0 on 2026-07-19 05:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_user_company_address_user_company_logo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='default_currency',
            field=models.CharField(choices=[('USD', 'USD — US Dollar'), ('EUR', 'EUR — Euro'), ('GBP', 'GBP — British Pound'), ('CAD', 'CAD — Canadian Dollar'), ('AUD', 'AUD — Australian Dollar'), ('NZD', 'NZD — New Zealand Dollar'), ('HKD', 'HKD — Hong Kong Dollar'), ('SGD', 'SGD — Singapore Dollar'), ('JPY', 'JPY — Japanese Yen'), ('CNY', 'CNY — Chinese Yuan'), ('PKR', 'PKR — Pakistani Rupee'), ('INR', 'INR — Indian Rupee'), ('BDT', 'BDT — Bangladeshi Taka'), ('AED', 'AED — UAE Dirham'), ('SAR', 'SAR — Saudi Riyal'), ('QAR', 'QAR — Qatari Riyal'), ('CHF', 'CHF — Swiss Franc'), ('SEK', 'SEK — Swedish Krona'), ('NOK', 'NOK — Norwegian Krone'), ('DKK', 'DKK — Danish Krone'), ('ZAR', 'ZAR — South African Rand')], default='USD', max_length=3),
        ),
    ]
