# Generated by Django 6.0.7 on 2026-08-04 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_user_default_currency'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='default_currency',
            field=models.CharField(choices=[('HKD', 'HKD - Hong Kong Dollar'), ('USD', 'USD — US Dollar'), ('EUR', 'EUR — Euro'), ('GBP', 'GBP — British Pound'), ('CAD', 'CAD — Canadian Dollar'), ('AUD', 'AUD — Australian Dollar'), ('PKR', 'PKR — Pakistani Rupee'), ('INR', 'INR — Indian Rupee'), ('AED', 'AED — UAE Dirham')], default='USD', max_length=3),
        ),
    ]
