# Generated by Django 6.0.7 on 2026-07-16 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0002_subscription_stripe_checkout_session_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscription',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('past_due', 'Past due'), ('cancelled', 'Cancelled'), ('expired', 'Expired')], default='active', max_length=20),
        ),
    ]
